### ISSUE TITLE
Can't get correct coinbase reward

### ISSUE THREAD

**Issue by poctek** [HarukaMa/aleo-explorer#2]
Hi! I'm digging into the explorer and trying to get how the rewards calculation works and can't get my head around it. I've checked out your rewards calculation code, extracted it into snippet, tried to get the same result as in the frontend, but getting different (bigger) rewards. What am I missing?

```python
def retarget(prev_target, prev_block_timestamp, block_timestamp, half_life, inverse, anchor_time):
    drift = max(block_timestamp - prev_block_timestamp, 1) - anchor_time
    if drift == 0:
        return prev_target
    if inverse:
        drift = -drift
    exponent = int((1 << 16) * drift / half_life)
    integral = exponent >> 16
    fractional = exponent - (integral << 16)
    fractional_multiplier = (1 << 16) + ((195_766_423_245_049 * fractional + 971_821_376 * pow(fractional, 2) + 5_127 * pow(fractional, 3) + pow(2, 47)) >> 48)
    candidate_target = prev_target * fractional_multiplier
    shifts = integral - 16
    if shifts < 0:
        candidate_target = max(candidate_target >> -shifts, 1)
    else:
        candidate_target = max(candidate_target << shifts, 1)
    candidate_target = min(candidate_target, 2 ** 64 - 1)
    return candidate_target

def get_coinbase_reward(current_height, current_timestamp, previous_timestamp) -> int:
    anchor_reward = 13
    y10_anchor_height = 31536000 // 25 * 10
    remaining_blocks = y10_anchor_height - current_height
    if remaining_blocks <= 0:
        return 0
    return retarget(remaining_blocks * anchor_reward, previous_timestamp, current_timestamp, 25, True, 25)

print(get_coinbase_reward(427323, 1674120477, 1674120464) // 2)
# => 110476440
```

The result in the frontend is 72.902145, I get 110.476440.

**Comment by HarukaMa** [comment]
I didn't check the data but I guess the reason is: The `previous_timestamp` here actually means "the timestamp of the last block that contains coin base reward", not just the previous block.

If the previous block actually contains coin base rewards, then 110 seems reasonable.

**Comment by poctek** [comment]
Yeah, it works! And maybe you could elaborate or point to the documentation: in which case it's possible that there's no coinbase reward in a block? I expected every block to have the coinbase reward

**Comment by poctek** [comment]
Thinking about coinbase reward, maybe block without coinbase rewards is a block without any coinbase solutions included?

**Comment by HarukaMa** [comment]
a very very _very_ late reply, but the above is correct.

Probably already solved a long time ago though, so I'm closing the issue.
