### ISSUE TITLE
type error when run main.py

### ISSUE THREAD

**Issue by WSbaikaishui** [HarukaMa/aleo-explorer#25]
```Traceback (most recent call last):
  File "/Users/mozes/workspace/test/aleo-explorer/main.py", line 7, in <module>
    from explorer import Explorer
  File "/Users/mozes/workspace/test/aleo-explorer/explorer/__init__.py", line 1, in <module>
    from .explorer import Explorer
  File "/Users/mozes/workspace/test/aleo-explorer/explorer/explorer.py", line 7, in <module>
    import webui
  File "/Users/mozes/workspace/test/aleo-explorer/webui/__init__.py", line 1, in <module>
    from .webui import run, app, run_profile
  File "/Users/mozes/workspace/test/aleo-explorer/webui/webui.py", line 19, in <module>
    from .chain_routes import *
  File "/Users/mozes/workspace/test/aleo-explorer/webui/chain_routes.py", line 12, in <module>
    import util.arc0137
  File "/Users/mozes/workspace/test/aleo-explorer/util/arc0137.py", line 9, in <module>
    from node.testnet3 import Testnet3
  File "/Users/mozes/workspace/test/aleo-explorer/node/__init__.py", line 2, in <module>
    from .node import Node
  File "/Users/mozes/workspace/test/aleo-explorer/node/node.py", line 12, in <module>
    from .testnet3.param import Testnet3
  File "/Users/mozes/workspace/test/aleo-explorer/node/testnet3/__init__.py", line 1, in <module>
    from .param import Testnet3
  File "/Users/mozes/workspace/test/aleo-explorer/node/testnet3/param.py", line 12, in <module>
    class Testnet3:
  File "/Users/mozes/workspace/test/aleo-explorer/node/testnet3/param.py", line 17, in Testnet3
    genesis_block = Block.load(BytesIO(open(os.path.join(os.path.dirname(__file__), "block.genesis"), "rb").read()))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/vm_block.py", line 3628, in load
    ratifications = Ratifications.load(data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/vm_block.py", line 3594, in load
    ratifications = Vec[Ratify, u32].load(data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/generic.py", line 125, in load
    return cls(list(value_type.load(data) for _ in range(size)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/generic.py", line 125, in <genexpr>
    return cls(list(value_type.load(data) for _ in range(size)))
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/vm_block.py", line 3189, in load
    return GenesisRatify.load(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/vm_block.py", line 3231, in load
    committee = Committee.load(data)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/vm_block.py", line 3214, in load
    members = Vec[Tuple[Address, u64, bool_], u16].load(data)
              ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/generic.py", line 33, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mozes/workspace/test/aleo-explorer/aleo_types/generic.py", line 96, in __class_getitem__
    raise TypeError(f"expected Serializable type, got {var_type}")
TypeError: expected Serializable type, got abc.Tuple[Address, u64, bool_][aleo_types.vm_basic.Address, aleo_types.basic.u64, aleo_types.basic.bool_]```

I followed the usage and this problem occurred.Is there something I missed?

**Comment by WSbaikaishui** [comment]
run it on macos14.1.2 (23B92) intel

**Comment by WSbaikaishui** [comment]
I solve this problem，but another comes，How to fix it？
<img width="1300" alt="image" src="https://github.com/HarukaMa/aleo-explorer/assets/46080358/abaaad50-34f2-4dce-ac28-288f14ef2945">

**Comment by HarukaMa** [comment]
Testnet beta branch should work without issue like this. Make sure you are using supported python version.

**Comment by WSbaikaishui** [comment]
the python version is 3.11.5, i think it works... and this is the testnet beta branch,

**Comment by HarukaMa** [comment]
3.11.5 indeed should work. Segfaults most probably come from the rust module, but I haven't tried to run it on macos before. From PyO3 document, it seems macOS needs extra arguments to build, but I think maturin should handle that?iPhoneから送信2024/06/18 18:43、Mozes ***@***.***>のメール:﻿
the python version is 3.11.5, i think it works... and this is the testnet beta branch,

**Comment by WSbaikaishui** [comment]
maturin doesn't work, I try to use maturin build, build success, but when we run the main.py, errors come again

**Comment by WSbaikaishui** [comment]
maybe aleo_explorer_rust is the reason,this is the bug code
```value_id = Field.loads(aleo_explorer_rust.get_value_id(str(key_id), value.dump()))```
insert.py

**Comment by HarukaMa** [comment]
It should not segfault. Most probably the built extension is somehow incompatible with the python version.
Unfortunately I don't have Mac devices around right now and can't test it right now. (I'm on 10.15.7 anyway so probably can't reproduce it as well)

**Comment by WSbaikaishui** [comment]
I try to use python 3.10.14, but another error comes,
<img width="960" alt="image" src="https://github.com/HarukaMa/aleo-explorer/assets/46080358/9f7f1dbf-13dd-47ba-876a-df83de2e4370">
maybe something wrong with it

**Comment by HarukaMa** [comment]
https://docs.python.org/3/library/enum.html#enum.EnumType
Apparently I need to remove 3.10 from readme...

**Comment by WSbaikaishui** [comment]
I will try to build on Ubuntu,so let us make sure that the branch  is right.
explorer :testnet-beta
rust:testnet-beta
is that all right?

**Comment by WSbaikaishui** [comment]
it works on linux... nothing happened, maybe macos needs more extra arguments

**Comment by WSbaikaishui** [comment]
I have a new discovery. I want to ask, if there is no information in the database, can this code run normally from 0?

**Comment by HarukaMa** [comment]
It's designed to sync from scratch.

**Comment by HarukaMa** [comment]
It will even wipe the database and restart from scratch if it detected that the database is not on the same network as the node.

**Comment by WSbaikaishui** [comment]
<img width="1143" alt="image" src="https://github.com/HarukaMa/aleo-explorer/assets/46080358/0b900c06-4a75-469a-b4b4-137735c706f5">
the leaderboard gets an error 500,and I find that the database have no table about leaderboard

**Comment by zkclay** [comment]
@WSbaikaishui this error appears in production as well, so this is a general bug, not an issue with your specific installation. I am thinking of taking a look at this PR and trying to contribute a PR to fix ii soon. 

https://testnet.aleoscan.io/leaderboard

**Comment by WSbaikaishui** [comment]
thanks for you reply, I got this ,and And I wish you can finish it soon.

> @WSbaikaishui this error appears in production as well, so this is a general bug, not an issue with your specific installation. I am thinking of taking a look at this PR and trying to contribute a PR to fix ii soon. 此错误也会出现在生产中，因此这是一个一般错误，而不是您的特定安装的问题。我正在考虑查看此 PR 并尝试贡献一个 PR 来尽快修复 ii。
> 
> https://testnet.aleoscan.io/leaderboard

**Comment by HarukaMa** [comment]
@zkclay The old leaderboard is deprecated and the removal of related tables are intentional. There might be similar features in the future, but I'm not sure at the moment.

Please don't try to revive the old leaderboard for the meantime.

**Comment by zkclay** [comment]
@HarukaMa sounds good, thanks for the context!
