### ISSUE TITLE
New Testnet Beta update

### ISSUE THREAD

**Issue by pl741** [HarukaMa/aleo-explorer#29]
The testnet beta network has been reset and data cannot be synchronized.

**Comment by HarukaMa** [comment]
work is being done for new network support. haven't pushed any commits yet but a big commit is on the way.

**Comment by zkclay** [comment]
@HarukaMa thanks !! appreciate it . I don't know if you had advanced notice of this, but it was unexpected for me so I appreciate you taking on this sudden work.

**Comment by WSbaikaishui** [comment]
> work is being done for new network support. haven't pushed any commits yet but a big commit is on the way.

I tried to make some new modifications, but I found that I couldn't obtain the latest block.genesis file. How is this file generated?

**Comment by HarukaMa** [comment]
@zkclay I was actually working on the canary net update before, but it's pretty hard to have work-work balance so it was progressing pretty slow during the month.

@WSbaikaishui for block.genesis: those are in snarkVM repo (`parameters/src/{network}/resources`). for dev.genesis: generate them by running a dev node on that network and you can find the genesis block in `/tmp`.

**Comment by WSbaikaishui** [comment]
@HarukaMa  thanks for your kind reply,  you did a great job
