### ISSUE TITLE
finialize problem

### ISSUE THREAD

**Issue by WSbaikaishui** [HarukaMa/aleo-explorer#32]
![image](https://github.com/HarukaMa/aleo-explorer/assets/46080358/ebbd14aa-9287-4be4-95b0-52dd313ed853)
when I start to sync node, It's failed, Is that node's problem ?

**Comment by WSbaikaishui** [comment]
i use the latest version

**Comment by HarukaMa** [comment]
Did you sync from genesis in one explorer run or have you restarted the explorer during the sync?

**Comment by WSbaikaishui** [comment]
yes, the explorer have an error about node disconnected, and I use another node and restat it

**Comment by HarukaMa** [comment]
How did you restart the explorer exactly?

**Comment by WSbaikaishui** [comment]
first, I set up .env file, using python main.py, and after a lot of blocks, node lose connection, I update the env file with another node, using python main.py to restart it



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/06/2024 18:41 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HarukaMa/aleo-explorer] finialize problem (Issue #32) |

How did you restart the explorer exactly?

**Comment by WSbaikaishui** [comment]
but this mistake not show at the begin, a lot of blocks sync,  error comes

**Comment by HarukaMa** [comment]
I mean, the exact method you have used to stop the explorer

**Comment by WSbaikaishui** [comment]
just ctrl+c

**Comment by HarukaMa** [comment]
with only 1 ctrl-c? that's strange as I've been doing that all the time to update it and I have some code to prevent corruptions when stopping it. Does it work if you resync from start?

**Comment by WSbaikaishui** [comment]
I will try it later

**Comment by WSbaikaishui** [comment]
if using kill -9, how to fix it ? or only resync from start?

**Comment by HarukaMa** [comment]
Do not ever use `kill -9` on anything please, you will be just asking for troubles if you do that

**Comment by HarukaMa** [comment]
You should never use `-9` unless you can't do anything else to any process

**Comment by WSbaikaishui** [comment]
okok，I get this, and is kill-15 works ? I want to write a shell to restart it



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/06/2024 19:51 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HarukaMa/aleo-explorer] finialize problem (Issue #32) |

Do not ever use kill -9 on anything please, you will be just asking for troubles if you do that

**Comment by HarukaMa** [comment]
it's the same as not giving `-15` actually, but I only use SIGINT (ctrl-c) and the code only blocks that one signal when running in certain sections, so there is no guarantee that SIGTERM won't corrupt anything.
Anyway, if you have been running the explorer for long enough, it will create "restore points" so you can revert to that point and sync from there. The default interval is 12 hours to reduce SSD wears. 
I'm not entirely sure of the exact reason of mapping corruption though. Being able to identify which code actually causes that would be very helpful.

**Comment by WSbaikaishui** [comment]
Thank you so much for taking the time to help me and answer these stupid questions.
and how to find "restore point",or I can see it

**Comment by HarukaMa** [comment]
Every 12 hours the explorer will make a copy of all current redis keys to new keys that contains `:history` and current block height. When you encounter corruptions, you can revert the whole explorer state to the latest history copy by creating a new file called `revert_flag` and start the explorer. The explorer will then remove the flag file and proceed to revert to that point. You can repeatedly do that to revert to an even earlier version, but to save disk space, I'm only storing the history for 3 days before purging them.
If you are using spinning disks that flash wear is not a concern, or you have some disk compression in place (redis data tend to compress well), you might try to make the interval shorter and keep longer history.

**Comment by HarukaMa** [comment]
For example:
![image](https://github.com/HarukaMa/aleo-explorer/assets/861659/50f5539f-87ac-4d5c-b8d0-7a6b2d37339c)
Ideally I'd save this for every block, but it would take huge amount of disk space to do that so I had to make some compromises there.

**Comment by WSbaikaishui** [comment]
crazy job！！！！！！ it's helpful for me
