### ISSUE TITLE
Running against a local devnet using more than 4 validators

### ISSUE THREAD

**Issue by evanmarshall** [HarukaMa/aleo-explorer#37]
I'm running in an issue trying to run the explorer against more than 4 validators. When using the ./devnet.sh script from snarkOS, I'm able to run a network with more than 4 validators.

Running the explorer locally with `docker-compose up` works wonderfully with exactly 4 validators but not more than 4.

I'm getting the following error:
```
Disconnected: InvalidChallengeResponse
haruka-aleo-explorer-harukamaaleoexplorer-1  | Traceback (most recent call last):
haruka-aleo-explorer-harukamaaleoexplorer-1  |   File "/app/node/node.py", line 72, in worker
haruka-aleo-explorer-harukamaaleoexplorer-1  |     size = await self.reader.readexactly(4)
haruka-aleo-explorer-harukamaaleoexplorer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
haruka-aleo-explorer-harukamaaleoexplorer-1  |   File "/usr/local/lib/python3.11/asyncio/streams.py", line 748, in readexactly
haruka-aleo-explorer-harukamaaleoexplorer-1  |     raise exceptions.IncompleteReadError(incomplete, n)
haruka-aleo-explorer-harukamaaleoexplorer-1  | asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes
haruka-aleo-explorer-harukamaaleoexplorer-1  | node disconnected
haruka-aleo-explorer-harukamaaleoexplorer-1  | 
haruka-aleo-explorer-harukamaaleoexplorer-1  | During handling of the above exception, another exception occurred:
haruka-aleo-explorer-harukamaaleoexplorer-1  | 
haruka-aleo-explorer-harukamaaleoexplorer-1  | Traceback (most recent call last):
haruka-aleo-explorer-harukamaaleoexplorer-1  |   File "/app/node/node.py", line 74, in worker
haruka-aleo-explorer-harukamaaleoexplorer-1  |     raise Exception("connection closed")
haruka-aleo-explorer-harukamaaleoexplorer-1  | Exception: connection closed
haruka-aleo-explorer-harukamaaleoexplorer-1  | node connected
haruka-aleo-explorer-harukamaaleoexplorer-1  | Disconnected: InvalidChallengeResponse
haruka-aleo-explorer-harukamaaleoexplorer-1  | Traceback (most recent call last):
haruka-aleo-explorer-harukamaaleoexplorer-1  |   File "/app/node/node.py", line 72, in worker
haruka-aleo-explorer-harukamaaleoexplorer-1  |     size = await self.reader.readexactly(4)
haruka-aleo-explorer-harukamaaleoexplorer-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
haruka-aleo-explorer-harukamaaleoexplorer-1  |   File "/usr/local/lib/python3.11/asyncio/streams.py", line 748, in readexactly
haruka-aleo-explorer-harukamaaleoexplorer-1  |     raise exceptions.IncompleteReadError(incomplete, n)
haruka-aleo-explorer-harukamaaleoexplorer-1  | asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes
```

Any tips? 

I've tried changing the port: https://github.com/HarukaMa/aleo-explorer/blob/testnet-beta/docker-compose.yml#L41 but so far no luck.

**Comment by HarukaMa** [comment]
Errors like this usually mean the explorer's node is being restricted by the snarkOS node (triggered spam protection). Usually it should resolve within a few minutes. Additionally for validator nodes, it might be recognized as untrusted external nodes by snarkOS thus cannot connect.
Is this error persistent and completely prevents the explorer from connecting even from first try?

**Comment by evanmarshall** [comment]
Yes, the error is persistent and continues indefinitely. I've attached a full logs file from running for 30+ minutes
[logs.txt](https://github.com/user-attachments/files/16536872/logs.txt)

The genesis block seems to load but otherwise, no blocks past genesis are synced.

**Comment by HarukaMa** [comment]
Ah, most likely with more than 4 validators the dev genesis has changed as well so the bundled genesis block doesn't match what's being used in your network.
You can find the genesis block generated by snarkOS in `/tmp`, then replacing the `node/{network}/dev.genesis` with that should work.

**Comment by evanmarshall** [comment]
That did the trick! Thank you so much.
