### ISSUE TITLE
I don't use vscode but I'd guess this file won't properly spin up a dev container to run the explorer. You probably want to at least add env preparation, port definition and more things like that before trying to merge this in.

### ISSUE THREAD

**Issue by Sabiiii9944** [HarukaMa/aleo-explorer#43]
I don't use vscode but I'd guess this file won't properly spin up a dev container to run the explorer. You probably want to at least add env preparation, port definition and more things like that before trying to merge this in.

_Originally posted by @HarukaMa in https://github.com/HarukaMa/aleo-explorer/issues/42#issuecomment-2430128189_

**Comment by HarukaMa** [comment]
?
