### ISSUE TITLE
The testnet explorer is out of sync

### ISSUE THREAD

**Issue by mumu714** [HarukaMa/aleo-explorer#46]
testnet.aleoscan.io
the explorer is out of sync. Current block height: explorer: 2315049.

**Comment by HarukaMa** [comment]
this will require some changes to the interpreter as it is referencing to the wrong transition id in multi transition txs. there were already some wrong reject messages in the database related to this.
i'm surprised your explorer is still running while keeping the interpreter mostly as is though.

**Comment by HarukaMa** [comment]
forgot to add that this has been fixed already.
